### ISSUE TITLE
FYI: voctoweb will provide a GraphQL API in near future

### ISSUE THREAD

**Issue by saerdnaer** [barnslig/mediacccde-graphql#3]
c.f. https://github.com/voc/voctoweb/pull/340

**Comment by barnslig** [comment]
Thank you very much for your hint!

I saw your pull request and I am very much looking forward for the official GraphQL-API! However, it felt to me as if the official GraphQL-API is not something that is going to happen tomorrow and still in need for a lot of thinking and programming until one can use it to build an actual client or even a new media.ccc.de.

This repository is more of a learner's project for me on my way to figure out how one builds a good schema, backend, deployment, caching etc.

It still might be that some parts of it can be beneficial for voctoweb's further development. For example, I spent some more time on building a good [schema](https://github.com/barnslig/mediacccde-graphql/blob/master/src/schema.graphql) that is eventually relay-compatible and easier to extend in the future after my first prototype and I figured out some more small itches on the public JSON API that I am going to submit pull requests for. I am also interested in helping out with the GraphQL integration.

So hopefully this is just part of the general improvements of voctoweb so one day we can have a media.ccc.de that is just as good as YouTube or even better so no one has to watch videos over there anymore ;D

Do you have an IRC channel or something related to voctoweb?

**Comment by saerdnaer** [comment]
There is ircs://irc.hackint.org/#voc-media, but our general public channel ircs://irc.hackint.org/#voc-lounge is normally more active.
